version: "3.9"

services:
    whoami:
        container_name: "whoami"
        image: "containous/whoami"
    frankenphp:
        container_name: "frankenphp"
        build:
            context: .
            dockerfile: frankenphp.Dockerfile
        ports:
            - "9804:9804"
